name: Build Ghostgram IPA
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-14
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Fix Submodules
        run: |
          # Исправляем пути, если они битые, и качаем части кода
          sed -i '' 's|../|https://github.com/TelegramMessenger/|g' .gitmodules
          git submodule sync
          git submodule update --init --recursive --depth 1

      - name: Prepare Files
        run: |
          # Создаем пустые конфиги, чтобы сборщик не ругался на их отсутствие
          mkdir -p build-input
          echo '{}' > build-system/appstore-configuration.json
          echo '{"api_id": 2040, "api_hash": "b18441a1ff607e10aee99999f35d94bd"}' > build-system/data-config.json

      - name: Build IPA
        run: |
          # Запускаем сборку именно для реального айфона (release_arm64)
          python3 build-system/Make/Make.py \
            --cacheDir="$HOME/telegram-bazel-cache" \
            build \
            --configurationPath=build-system/appstore-configuration.json \
            --buildNumber=100 \
            --configuration release_arm64 \
            --xcodeManagedCodesigning \
            --overrideXcodeVersion

      - name: Upload IPA
        uses: actions/upload-artifact@v4
        with:
          name: Ghostgram-IPA
          path: build/artifacts/*.ipa
